### ISSUE TITLE
polyfill-corejs3 won't polyfill some Promise static methods with method: "usage-pure"

### ISSUE THREAD

**Issue by giniyat202** [babel/babel-polyfills#105]
I've been experimenting with `polyfill-corejs3` a bit and tried the following setup (also on this repo https://github.com/giniyat202/babel-polyfill-promise):

.browserslist:
```
chrome >= 75
```

.babelrc:
```json
{
  "presets": ["@babel/preset-env"],
  "plugins": [
    [
      "polyfill-corejs3",
      {
        "method": "usage-pure"
      }
    ]
  ]
}
```

input.js:
```js
Promise.all();
Promise.allSettled();
Promise.any();
Promise.race();
```

I'm expecting both `Promise.allSettled` and `Promise.any` to be polyfilled. However, this is not the case here.

expected output:
```js
"use strict";

var _allSettled = _interopRequireDefault(require("core-js-pure/features/promise/all-settled.js"));

var _any = _interopRequireDefault(require("core-js-pure/features/promise/any.js"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

Promise.all();
(0, _allSettled.default)();
(0, _any.default)();
Promise.race();
```

actual output:
```js
"use strict";

Promise.all();
Promise.allSettled();
Promise.any();
Promise.race();
```

`usage-global` correctly provides the two missing polyfills.

I've noticed that these methods are defined without a `pure` reference:
https://github.com/babel/babel-polyfills/blob/fa4f9f3c42d50702b69f2aa8943840a5ba42c3fe/packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.js#L338-L350

I've tried passing `"promise/all-settled"` and `"promise/any"` there and I started seeing correct output.

**Comment by nyngwang** [comment]
Does this issue mean that `usage-pure` is still buggy and it should be avoided in production?

**Comment by zloirock** [comment]
That means that `usage-pure` is still buggy with targets.  https://github.com/babel/babel-polyfills/pull/198 adds a kind of workaround for that.

**Comment by nyngwang** [comment]
@zloirock Oh thank you so much :) Just a little question: if I want to contribute to this project like he/she did in the PR, what should I do?

**Comment by zloirock** [comment]
@nyngwang look at https://github.com/babel/babel-polyfills/blob/main/CONTRIBUTING.md and https://github.com/babel/babel/blob/main/CONTRIBUTING.md.
