### ISSUE TITLE
[Bug]: preset-env with "debug: true" lists every target rather than the one which caused the polyfill

### ISSUE THREAD

**Issue by use** [babel/babel-polyfills#110]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
// code doesn't really matter, it just needs to cause some polyfills
[...document.querySelectorAll('.something')].forEach(
    (el) => el.classList.remove('something')
);
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "debug": true,
        "targets": [
          "> 0.25%",
          "not dead",
          "not IE 11"
        ],
        "useBuiltIns": "usage",
        "corejs": "3.6.5"
      }
    ]
  ]
}
```

### Current behavior (started in 7.13.0):
preset-env with "debug: true" lists every target next to every applied polyfill, rather than only the target which caused the polyfill.

Example current behavior:
```
[babel-polyfill-test/src/test.js]
The corejs3 polyfill added the following polyfills:
  es.object.to-string { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
  web.dom-collections.for-each { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
  es.symbol { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
  es.symbol.description { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
  es.symbol.iterator { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
  es.array.iterator { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
  es.string.iterator { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
  web.dom-collections.iterator { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
  es.array.from { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
  es.array.slice { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
  es.regexp.exec { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
  es.regexp.test { "android":"4.4.3", "chrome":"92", "edge":"96", "firefox":"94", "ios":"12.2", "opera":"81", "safari":"13.1", "samsung":"15" }
```

### Expected behavior (last working version was 7.12.17):
Show the specific targets which caused each polyfill.

Example expected behavior, which is how it worked up to and including 7.12.17:
```
[babel-polyfill-test/src/test.js] Added following core-js polyfill:
  web.dom-collections.for-each { "android":"4.4.3" }
```

### Environment

@babel/preset-env@7.16.7
node v16.13.1
npm 8.1.2
Ubuntu 20.04

**Comment by nyngwang** [comment]
.@nicolo-ribaudo: This is not a bug. He is using `@babel/preset-env`. I don't think this issue is appropriate here.

> ```
> // code doesn't really matter, it just needs to cause some polyfills
> ...
> ```

@use This line is rude too. The input code **does matter**. I just tried the same config setup as you but I cannot reproduce it. Please update your question.

**Comment by dreyks** [comment]
I don't know which part broke it and when, but babel-preset-env's [logPlugin](https://github.com/babel/babel/blob/0416f165a89e90e476d46fc7acfdace16f568923/packages/babel-preset-env/src/debug.ts#L10) accepts an entire support object (object whose keys are polyfill names and values are support matrixes), but babel-helper-define-polyfill-provider [passes](https://github.com/babel/babel-polyfills/blob/ce30946033aaed0ae1daf09a75e76acf4d24b8cc/packages/babel-helper-define-polyfill-provider/src/index.ts#L225) just the support matrix for a given polyfill

changing this line https://github.com/babel/babel-polyfills/blob/ce30946033aaed0ae1daf09a75e76acf4d24b8cc/packages/babel-helper-define-polyfill-provider/src/index.ts#L225 to just `polyfillsSupport,` fixes the issue

**Comment by nicolo-ribaudo** [comment]
> however, this would not be a good change. instead, debugLog.polyfills should probably be a Set and just hold the selected polyfills, while the entire polyfillsSupport should be a separate key in debugLog

This sounds like the correct solution! Would you be interested in opening a PR?

**Comment by dreyks** [comment]
#137
