### ISSUE TITLE
Promise is polyfilled when using `.toArray`, even if supported by browser

### ISSUE THREAD

**Issue by dosentmatter** [babel/babel-polyfills#123]
```
npm install @babel/core @babel/cli babel-plugin-polyfill-corejs3 core-js
```

Versions:
```sh
% npm ls babel-plugin-polyfill-corejs3 @babel/core @babel/cli browserslist caniuse-lite
/Users/dosentmatter/babel
├── @babel/cli@7.17.6 
├─┬ @babel/core@7.17.9 
│ └─┬ @babel/helper-compilation-targets@7.17.7
│   └─┬ browserslist@4.20.2 
│     └── caniuse-lite@1.0.30001327 
└─┬ babel-plugin-polyfill-corejs3@0.5.2 
  └─┬ core-js-compat@3.21.1
    └── browserslist@4.20.2  deduped
```

```json
// .babelrc
{
  "plugins": [
    ["polyfill-corejs3", { "method": "usage-global" }]
  ]
}
```

I initially noticed issue when using `React.Children.toArray`, but it seems to happen with use of `.toArray` with any variable, eg. `_.toArray`.

Examples:
```js
// all browsers that don't support promises will polyfill Promise
% echo '_.toArray' | BROWSERSLIST='> 0% and not supports promises' npx babel -f stdin.js
"use strict";

require("core-js/modules/es.object.to-string.js");

require("core-js/modules/es.promise.js");

_.toArray;
```

```js
// All browsers that support promises still polyfills Promise
% echo '_.toArray' | BROWSERSLIST='supports promises' npx babel -f stdin.js
"use strict";

require("core-js/modules/es.object.to-string.js");

require("core-js/modules/es.promise.js");

_.toArray;
```

```js
// Modern browsers still polyfills Promise
% echo '_.toArray' | BROWSERSLIST='supports es6-module' npx babel -f stdin.js
"use strict";

require("core-js/modules/es.promise.js");

_.toArray;
```

```js
// Modern browsers using React.Children.toArray still polyfills Promise
% echo 'require("react").Children.toArray' | BROWSERSLIST='supports es6-module' npx babel -f stdin.js
"use strict";

require("core-js/modules/es.promise.js");

require("react").Children.toArray;
```

```js
// Modern browsers using someVariableName.toArray still polyfills Promise
% echo 'someVariableName.toArray' | BROWSERSLIST='supports es6-module' npx babel -f stdin.js
"use strict";

require("core-js/modules/es.promise.js");

someVariableName.toArray;
```

**Comment by dosentmatter** [comment]
I think it's related to this:

https://github.com/babel/babel-polyfills/blob/babel-plugin-polyfill-corejs3%400.5.2/packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.js#L785-L790

`AsyncIteratorDependencies` has `PromiseDependencies`:
https://github.com/babel/babel-polyfills/blob/babel-plugin-polyfill-corejs3%400.5.2/packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.js#L171

https://github.com/babel/babel-polyfills/blob/babel-plugin-polyfill-corejs3%400.5.2/packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.js#L90

From the original post, `es.object.to-string` gets removed when the browerslist config is modern enough. But for some reason `es.promise` isn't removed.

**Comment by zloirock** [comment]
Because it's not supported in those targets?  `caniuse` data is too naive in most cases, see [`core-js-compat` data](https://github.com/zloirock/core-js/blob/1f6985c158bc9c80562bd91f4a19d583108fac01/packages/core-js-compat/src/data.mjs#L897-L902).

**Comment by zloirock** [comment]
The problem is that `PromiseDependencies` are required only for `esnext.async-iterator.to-array`, this module is injected only in case of `proposals: true` flag (it's even not documented) - but dependencies of this module injected even without this flag. So required something like conditional dependencies.

**Comment by dosentmatter** [comment]
Thanks for the quick reponse.

Oh alright. I was under the impression that babel-polyfills using `browserslist` and `caniuse-lite` to figure out what to polyfill. I didn't know that `core-js` maintained it's own compat data.

So then is caniuse not used for compat data at all? Is it just used for `browserslist` to query for a list of supported browser versions and the `core-js` compat data is solely used for determining if a browser version supports a feature?

How does `core-js` collect its compat data and how does it compare to `caniuse`? What makes `caniuse` naive?


Oh I found the proposal for `esnext.async-iterator.to-array` in [proposal-iterator-helpers](https://tc39.es/proposal-iterator-helpers/#sec-asynciteratorprototype.toarray). Didn't know that existed. So I guess babel polyfills whenever `.toArray` shows up because any object can possibly an `AsyncIterator`?

I'm not sure I understand why this would happen:
> dependencies of this module injected even without this flag
If proposals aren't turned on and `esnext.async-iterator.to-array` isn't polyfilled, why would the `promise` dependency` get polyfilled?

---


I can confirm that transpilation matches the core-js compat data that you linked:
```js
% echo '_.toArray' | BROWSERSLIST='Chrome 66' npx babel -f stdin.js
"use strict";

require("core-js/modules/es.promise.js");

_.toArray;

% echo '_.toArray' | BROWSERSLIST='Chrome 67' npx babel -f stdin.js
"use strict";

_.toArray;
```

I'll close this issue since it's not a bug.

**Comment by zloirock** [comment]
> Is it just used for `browserslist` to query for a list of supported browser versions and the `core-js` compat data is solely used for determining if a browser version supports a feature?

Yes.

> How does `core-js` collect its compat data and how does it compare to `caniuse`? What makes `caniuse` naive?

[The test case based on `core-js` feature detection.](https://github.com/zloirock/core-js/blob/1f6985c158bc9c80562bd91f4a19d583108fac01/tests/compat/tests.js). `caniuse` in most just check existence of the feature without check on completeness, following the latest standards and bugs.

> So I guess babel polyfills whenever `.toArray` shows up because any object can possibly an `AsyncIterator`?

Yes.

> If proposals aren't turned on and `esnext.async-iterator.to-array` isn't polyfilled, why would the promise dependency` get polyfilled?

Because this plugin haven't a way to define conditional dependencies.
