### ISSUE TITLE
Cannot read properties of undefined (reading 'prototype') (>0.5.2)

### ISSUE THREAD

**Issue by icatalina** [babel/babel-polyfills#130]
⚠️ This seems like a regression between 0.5.1 and 0.5.2.

Hi!

When running `webpack` with `mini-css-extract-plugin` we are facing this issue.

```
TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.<anonymous> (/dev/repo/node_modules/source-map-loader/dist/cjs.js!/dev/repo/node_modules/core-js/modules/web.dom-exception.stack.js:31:74)
```

```ts
var DOMExceptionPrototype = $DOMException.prototype = NativeDOMException.prototype;
```

`NativeDOMException` seems to be undefined, causing the whole thing to trip over.

Node v14 and v16
npm@6
webpack 5

**Comment by nicolo-ribaudo** [comment]
What's your Babel configuration?

**Comment by zloirock** [comment]
The problem in your configuration, see https://github.com/zloirock/core-js/issues/1067.

**Comment by icatalina** [comment]
Hi @zloirock and @nicolo-ribaudo,

Thank for your prompt responses. I found https://github.com/zloirock/core-js/issues/1067 before posting this one, but it looks like an issue at runtime. In my case, it is webpack that blows up. I can't compile the application. I'm sure they are related, but I'm not sure they are the exact same problem.

I've tried downgrading all my dependencies back to their previous versions, and the only one that triggered the problem was `babel-plugin-polyfill-corejs@0.5.2`.

I'll try to get a minimal repo reproducing the issue and do some more testing tomorrow, I raised this while I was leaving the office.

Thanks 🙇

**Comment by zloirock** [comment]
@icatalina 
```
TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.<anonymous> (/dev/repo/node_modules/source-map-loader/dist/cjs.js!/dev/repo/node_modules/core-js/modules/web.dom-exception.stack.js:31:74)
```
is a runtime error. I could happen only if `DOMExeption` is missed - that could happen only in case if `web.dom-exception.constructor` is not loaded before `web.dom-exception.stack`. But this plugin should load it for required targets - like Node < 17 or old browsers. So the problem in your configuration. You are not the first or second who faced with issue.

**Comment by icatalina** [comment]
Hi @zloirock!

You are right, this is a "runtime error", but it happens during the compile step of our app. It also seems like a configuration issue, as you correctly pointed out.

I didn't expect webpack & babel to pick up source files from a loader. (eg. it is trying to process and polyfill some of the `css-loader` source files).

After some digging, it seems like we are not the only ones facing this issue, the solution seems to be to exclude certain dependencies from the transpilation in webpack: https://github.com/vuejs/vue-cli/blob/ce97e62304e884c4277aaa1b605f735253e4205b/packages/@vue/cli-plugin-babel/index.js#L71-L80

PS: Thanks for everything you do 👏
