### ISSUE TITLE
[Bug] The import path for core-js-pure output by babel-plugin-polyfill-corejs3 does not exist

### ISSUE THREAD

**Issue by Thiry1** [babel/babel-polyfills#141]
## Input code
console.log(/foo/.test(""));

## Configuration file name
.babelrc.js

## Configuration
```js

module.exports = {
  plugins: [
    [
      'babel-plugin-polyfill-corejs3',
      {
        method: 'usage-pure',
        version: '3.20',
      },
    ],
  ],
};

```
## Current and expected behavior
Current result:
```js
var _context;

import _testInstanceProperty from "core-js-pure/stable/instance/test.js"; // <- invalid path
console.log(_testInstanceProperty(_context = /foo/).call(_context, ""));
```

Expect result:
I'm not sure, but import path should be `core-js-pure/stable/regexp/test.js`?

Here's reproduction repo
https://github.com/Thiry1/babel-plugin-polyfill-corejs3-bug-repro

**Comment by nicolo-ribaudo** [comment]
@zloirock Is it intentional that some instance methods are in the `instance` folder, while some are not?

**Comment by zloirock** [comment]
Yes. It's available only for methods available in the pure version. [`.test` is not one of them](https://github.com/zloirock/core-js/blob/ff4f391f579eadf021bfcee41eab6c56b8816e3a/packages/core-js-pure/override/modules/es.regexp.test.js).

**Comment by Thiry1** [comment]
Thank you for quick reply.

So can't we polyfill `.test` without global pollution?

**Comment by zloirock** [comment]
`.test` is polyfilled for support delegation to `.exec` -> support modern features of the `RegExp` constructor. Since those `RegExp` features / `RegExp` constructor are not polyfilled in the pure version, polyfilling of `.test` have no big sense.

**Comment by nicolo-ribaudo** [comment]
So the bug is that we attempt to polyfill test even in the pure version; I'll fix it later this week.

**Comment by Thiry1** [comment]
@nicolo-ribaudo I have created a PR, can you check it out?
https://github.com/babel/babel-polyfills/pull/142
