### ISSUE TITLE
[Bug]: `babel-plugin-polyfill-corejs3` injects imports from non-existent modules in `core-js-pure` when `version` is specified

### ISSUE THREAD

**Issue by ernestostifano** [babel/babel-polyfills#152]
## Issue Description

After running Babel through `babel-loader` on an application's dependencies, at some point, the compilation breaks due to the following error:

```bash
Failed to compile.

Module not found: Error: Can't resolve 'core-js-pure/stable/instance/dot-all.js' in '/path/to/repo/.yarn/cache/regexp.prototype.flags-npm-1.4.3-df1c08b65d-51228bae73.zip/node_modules/regexp.prototype.flags'
```

The thing is that, inspecting the installed `core-js-pure` package, `dot-all.js` actually does not exist under `core-js-pure/stable/instance/` directory.

## Additional Notes
- If I don't pass `version` in `polyfill-corejs3` options, everything work as expected (all polyfills are correctly imported and there are no errors during compilation).
- If I pass '3.25.5' instead of '^3.25.2', it still does not work.

## Relevant Babel Plugin's Setup

```js
const plugins = [
    [
        '@babel/plugin-transform-runtime',
        {
            version: '^7.19.0'
        }
    ],
    [
        'polyfill-corejs3',
        {
            method: 'usage-pure',
            version: '^3.25.2'
        }
    ]
];
```

## Relevant `package.json` Versions

```json
{
    "dependencies": {
        "@babel/runtime": "^7.19.0",
        "core-js-pure": "^3.25.2"
    },
    "devDependencies": {
        "@babel/plugin-transform-runtime": "^7.19.1",
        "babel-plugin-polyfill-corejs3": "^0.6.0"
    }
}
```

## Exact Installed Versions

`@babel/runtime`: 7.19.4
`core-js-pure`: 3.25.5
`@babel/plugin-transform-runtime`: 7.19.6
`babel-plugin-polyfill-corejs3`: 0.6.0

**Comment by nyngwang** [comment]
@ernestostifano Where did you find the docs saying that non-exact `version` string like you did `^3.25.2` can be passed in?

**Comment by zloirock** [comment]
@nyngwang [`semver`](https://github.com/npm/node-semver) parses such strings as required, someone relies on versions from `package.json` where used `^`, so it's OK.
