### ISSUE TITLE
preset-env doesn't import "array.push" polyfill

### ISSUE THREAD

**Issue by Lancernix** [babel/babel-polyfills#159]
env targets is set `chrome 60` and compile below code:
```js
const cc = [1, 2].push(1);
```
different results were output using Babel and swc.
```js
// swc
import "core-js/modules/es.array.push.js";
const cc = [1, 2].push(1);

// babel
"use strict";
const cc = [1, 2].push(1);
```
swc repl:
https://play.swc.rs/?version=1.3.41&code=H4sIAAAAAAAAA0vOzysuUUhWsFWINtQx0jHWMYnVKygtztAw1bQGAKMvA4McAAAA&config=H4sIAAAAAAAAA0WOXQrCQAyEryJ5LiKKBXsEwUOENa0r3R%2BSrViWvbvZpdK3ZGbyZTK8xcCQISILcZ1k9Qm%2FMAAZh2LYxgSdxlQacRYqHSTkiVKNyFW9OQShze3AWW%2FHtZJMcJFJZLfQT%2FM%2FWRTkwnOpQoa0RmrAHsrO2O6sPLZg4kV38p9202ooHsyLg6NDf9I2JjDdq3g5nm%2FQflTyIjgRlPIDGgkQX%2FIAAAA%3D
Babel code screenshot:
![image](https://user-images.githubusercontent.com/26547236/226600480-90b22ea9-2111-472c-a781-4053f8704dc6.png)

related issue: https://github.com/swc-project/swc/issues/7100

core-js author @zloirock said that `Array.prototype.push` is buggy even in the latest Chrome, so it should be injected. Is that so?

**Comment by liuxingbaoyu** [comment]
This seems to have been fixed in the latest version of Babel.
