### ISSUE TITLE
Mention the rfc to move targets top level in the readme?

### ISSUE THREAD

**Issue by hzoo** [babel/babel-polyfills#18]
Using this makes it clear we don't want to have different sets of target options https://github.com/babel/rfcs/pull/2

```
{
  "presets": [
    ["@babel/preset-env", {
      "targets": ">1%, not ie 11"
    }]
  ],
"plugins": [
    [
      "babel-plugin-polyfill-corejs3",
      {
        "method": "usage-global",
        "targets": {
          "edge": 16
        }
      }
    ]
  ]
}
```

**Comment by agilgur5** [comment]
I believe this was at least partially completed by https://github.com/babel/babel-polyfills/commit/1694f0c0eb8cf5cbbcdc5fd7880a07b4a4b93a5d , which added a link to the RFC in the Migration docs (which are mentioned in the README).

But in any case, the RFC has been implemented now and https://github.com/babel/babel-polyfills/commit/1091fa4e27a597148403545d21e776dadeb5c518 changed the examples to use top-level targets, so I think this can almost certainly be closed now
