### ISSUE TITLE
dom-exception polyfill import fails

### ISSUE THREAD

**Issue by vskh** [babel/babel-polyfills#185]
Hello,

When I try to transpile the following snippet of code (does not make much sense, just to trigger polyfilling):
```
const e = new Error();

if (e instanceof DOMException) {
  console.log("DOMException");
}
```

babel produces the following output:

```
import t from "core-js-pure/stable/dom-exception.js";
new Error() instanceof t && console.log("DOMException");
```
However, if I look into content of the latest core-js-pure package (v3.33.0), there is no "core-js-pure/stable/dom-exception.js", instead there is "core-js-pure/stable/dom-exception" directory so import resolution fails.

Package versions involved:
- "@babel/preset-env": "7.22.15",
- "@babel/runtime-corejs3": "7.23.1",
- "babel-plugin-polyfill-corejs3": "0.8.4",
- "core-js-pure": "3.33.0"

Relevant config:
```
  presets: [
    [
      "@babel/preset-env",
      {
        targets: "> 1%, Firefox ESR, not dead, ie 11"
      }
    ],
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  plugins: [
    ["@babel/plugin-transform-runtime"],
    [
      "polyfill-corejs3",
      {
        method: "usage-pure",
        version: "3.32.2"
      }
    ]
  ]
```

Could you advise, if this is an issue with babel-polyfill or some breaking change in core-js and what's best way to go around it?

**Comment by zloirock** [comment]
It should be `import t from "core-js-pure/stable/dom-exception/index.js";`.

**Comment by zloirock** [comment]
[Line to fix.](https://github.com/babel/babel-polyfills/blob/4fd37c2bf72ab1869a3f8e26370421c91f8cca32/packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.ts#L250)

**Comment by zloirock** [comment]
I was hoping here was some index resolution logic -)

**Comment by vskh** [comment]
Thank you, created PR here: #186

**Comment by zloirock** [comment]
Several adjacent definitions, like `DisposableStack`, have the same problem.

**Comment by zloirock** [comment]
> Several adjacent definitions, like `DisposableStack`, have the same problem.

Reopening until they will be fixed.
