### ISSUE TITLE
core-js polyfill: incorrect import paths

### ISSUE THREAD

**Issue by andornaut** [babel/babel-polyfills#28]
Some imports such as eg. `Symbol` (and others) cannot be resolved, b/c the import paths are incorrect.

With `proposals: false`:
```
ERROR in ./src/SNIP
Module not found: Error: Can't resolve 'core-js-pure/stable/symbol.js' in '/home/andornaut/workspace/SNIP...'
```

This doesn't work because simbol is in core-js-pure/features/. When I change the configuration to `proposals: true`, then the `Symbol` ponyfill is looked up in core-js-pure/features/ as expected, but the module path is incorrect:
```
ERROR in ./src/SNIP
Module not found: Error: Can't resolve 'core-js-pure/features/symbol.js' in '/home/andornaut/workspace/SNIP...'
```

It attempts to import Symbol at core-js-pure/features/symbol.js, but the module is actually located at core-js-pure/features/symbol/index.js.

On my codebase this issue occurs for the following paths:

```
core-js-pure/features/map.js
core-js-pure/features/promise.js
core-js-pure/features/set.js
core-js-pure/features/symbol.js
```

In each case the correct path is the `${sibling directory of the same name without the extension}/index.js` and this is true of core-js and core-js-pure, eg. `node_modules/core-js/features/symbol/index.js` and `node_modules/core-js-pure/features/symbol/index.js`

Note that I also see this issue with plugin: "polyfill-corejs2" and core-js@2

For instance, this error:
```
Module not found: Error: Can't resolve 'core-js/library/fn/symbol.js
```
Where the module is actually in node_modules/core-js/library/fn/symbol/index.js

## Environment
 .babelrc.js
```
module.exports =
  {
  presets: [
    "@babel/preset-env"
  ],
  plugins: [
    '@babel/plugin-transform-react-jsx',
    '@babel/transform-runtime',
    ["polyfill-corejs3", {
      method: "usage-pure",
      proposals: true,
    }]
  ]
};
```

 .browserslistrc 
```
> 1%
ie >= 11
```

**Comment by anilanar** [comment]
```
Error: Can't resolve 'core-js-pure/stable/promise.js'
```

That file obviously doesn't exist. It should've been `core-js-pure/stable/promise`.

```
safari >= 11
iOS >= 10
last 3 Chrome versions
last 3 Edge versions
last 3 Firefox versions
last 3 ChromeAndroid versions

> 5% not dead
not IE 11
not IE_Mob 11
```

**Comment by ljharb** [comment]
@anilanar those are identical in node's resolution algorithm, which applies to node packages.

**Comment by nicolo-ribaudo** [comment]
@ljharb Not if the correct path is `core-js-pure/stable/promise/index.js`

**Comment by ljharb** [comment]
@nicolo-ribaudo aha, you're right :-)
