### ISSUE TITLE
How do I test / use this library as it is atm?

### ISSUE THREAD

**Issue by Fuzzyma** [babel/babel-polyfills#29]
I am aware that this repo is still experimental but I don't wanna wait.
I already tried my luck using it but I failed.

How do you actually use this repo atm? The packages are not listed on npm yet so how do you wire everything up so that it works?

Ofc I would report back my findings once it is working :)

**Comment by nicolo-ribaudo** [comment]
These packages are already on npm! You can try `babel-plugin-polyfill-es-shims` and `babel-plugin-polyfill-corejs3`.

**Comment by Fuzzyma** [comment]
Awesome! Will try asap :)
