### ISSUE TITLE
Is there a prefered way to use with preset-env useBuiltIns but no polyfills

### ISSUE THREAD

**Issue by jquense** [babel/babel-polyfills#30]
Sorry for badly titled issue, unsure how to describe this succinctly. We are trying to use babel-polyfills with preset-env but running into an issue where it's not easy to tell preset-env plugins to use builtins _without also polyfilling them_. In an example 

```
const a = {}
const b = { ...a}
```
Would include an `_extends` helper if `useBuiltIns` is false. Setting it to usage compiles to `Object.assign({}, a)` which is great but also includes a core-js polyfill. We are currently working around this by doing `exclude=[/^(es|es6|es7|esnext|web)\./]` which works but feels less than ideal.

**Comment by nicolo-ribaudo** [comment]
Yeah overloading `useBuiltIns` for two different things wasn't probably a good idea :thinking: 

The best workaround I can think of is to explicitly include the object-rest-spread plugin:

```json
{
  "presets": [
    ["@babel/preset-env", { "useBuiltIns": false, "exclude": ["proposal-object-rest-spread"] }],
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-object-rest-spread",
      { "useBuiltIns": true },
    ],
  ],
}
```
