### ISSUE TITLE
Unsure how usage-pure and transform-runtime should work

### ISSUE THREAD

**Issue by jquense** [babel/babel-polyfills#32]
Sorry for the slew of issues, we are really testing out the work here (it's awesome!). The docs [suggest](https://github.com/babel/babel-polyfills/blob/main/docs/migration.md#core-js3) that this can be used instead of corejs specific runtime packages: 

```js
{
  "presets": [
    ["@babel/preset-env", {
      "targets": { "firefox": 42 }
    }]
  ],
  "plugins": [
    ["@babel/transform-runtime", {
      "corejs": 3
    }]
  ]
}
```

It's unclear to me though how this would work for helpers that _also_ need polyfills. like AsyncGenerator. Is this case supposed to be covered?

**Comment by nicolo-ribaudo** [comment]
When designing these plugins, I decided to threat `@babel/runtime` as a normal dependency: you compile it if you need. Note that this wasn't possible in the past and caused recursion errors in the compiled output, but it's safe since Babel 7.8.4 [it is safe](https://github.com/babel/babel/pull/11049).

I would thus configure Babel like this:
```json
// babel.config.json
{
  "overrides": [{
    "test": "./src",
    "presets": [
      ["@babel/preset-env", {
        "targets": { "firefox": 42 }
      }]
    ],
    "plugins": [
      "@babel/transform-runtime"
    ]
  }, {
    "test": ["./src", "./node_modules/@babel/runtime"],
    "plugins": [
      ["polyfill-corejs3", {
        "method": "usage-pure",
        "targets": { "firefox": 42 }
      }]
    ]
  }]
}
```

**Comment by nicolo-ribaudo** [comment]
Demo: https://github.com/nicolo-ribaudo/repro-babel-polyfills-32 (`npm ci` and `./node_modules/.bin/webpack`)

**Comment by jquense** [comment]
sweet, makes sense 👍
