### ISSUE TITLE
General timeline for mainstream usage?

### ISSUE THREAD

**Issue by dlong500** [babel/babel-polyfills#34]
I see the repo still notes that these packages are "highly experimental" and "have not been tested in production".  Is there a plan for when these will no longer be experimental?  No pressure; just trying to get a sense of when this will become the recommended way to deal with polyfills (and/or if there are still some competing ideas within the babel ecosystem in regards to polyfilling).

**Comment by nicolo-ribaudo** [comment]
Before releasing a stable version, I'd like to provide support for at least two alternative polyfills.
At the moment `core-js@3` is fully supported, and I'm working with the `es-shims` maintainers to add full ES6 support (at least).

Then, I hope to deprecate `@babel/preset-env`'s `useBuiltIns` in favor of these packages in Babel 8 :smile:
