### ISSUE TITLE
polyfill-regenerator doesn't support targets

### ISSUE THREAD

**Issue by agilgur5** [babel/babel-polyfills#36]
## Issue

Hey there, so I've been trying to add this to [TSDX](https://github.com/formium/tsdx) in https://github.com/formium/tsdx/pull/795 but ran into an issue: https://github.com/formium/tsdx/pull/795#issuecomment-694697396. Long story short, `polyfill-regenerator` doesn't seem to support `targets`.

If I'm understanding correctly, [this line](https://github.com/babel/babel-polyfills/blob/3bb29d0b7c18e1baf9227481c03bff20a5854860/packages/babel-plugin-polyfill-regenerator/src/index.js#L9) needs to specify `targets` per [the `polyfill-provider` docs](
https://github.com/babel/babel-polyfills/blob/main/docs/polyfill-provider.md#providerpolyfills-string---name-string-support-).

Would be happy to write a PR for this and will look into it more tomorrow. I'm not sure if I should just manually input [the data from MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*#Browser_compatibility) or if I should use `babel-compat-data` [for `transform-regenerator`](https://github.com/babel/babel/blob/44f8287d7ac3c523a9425a7bb4beb4882090ae20/packages/babel-compat-data/data/plugins.json#L372)? Any guidance would be appreciated

## Context

Per above, was looking to get this to work with [TSDX](https://github.com/formium/tsdx), which would add quite a lot of indirect library users of this.

Concretely, I was adding this to replace the now defunct/unmaintained [`babel-plugin-async-to-promises`](https://github.com/rpetrich/babel-plugin-transform-async-to-promises) (that has some [correctness](https://github.com/formium/tsdx/labels/topic%2Fasync-to-promises) [bugs](https://github.com/rpetrich/babel-plugin-transform-async-to-promises/issues)) without the downsides of an impure `preset-env` `useBuiltIns` or all-or-nothing `transform-runtime`.

## P.S.

Also just wanted to say really happy to see this set of libraries existing to provide a solution for gaps between `preset-env` `useBuiltIns` and `transform-runtime`, solves a long existing problem!

**Comment by nicolo-ribaudo** [comment]
I didn't implement `targets` support for `polyfill-regenerator` because I don't think it would give any advantage. The `regenerator-runtime` library is necessary only and always when you compile generators.

`@babel/plugin-transform-regenerator` injects a call to a global `regeneratorRuntime` variable, and `polyfill-regenerator` detects this injected variable usage and injects the polyfill when it's present.

This means that, even if you always enable the polyfill plugin, it only does something when you transpile generators.

I think that allowing `targets` for `polyfill-regenerator` can only cause problems, in case the targets or compat data of the `transform-regenerator` and `polyfill-regenerator` get out of sync.

However, maybe we could throw a better error message :thinking:

**Comment by agilgur5** [comment]
Ohhhh gotcha, so it'll only run if `transform-regenerator` has already run basically, so only to configure `preset-env`'s `targets`.

That's great, then I don't need to duplicate `targets` either! Thanks for the quick and informative response 🙂 

Yea I think a warning or error logged out if `targets` is used would be helpful. Right now it doesn't log at all, basically just ignores `targets`. A small note on this in the docs would be useful too since this behaves differently / doesn't need `targets` duplication unlike the other polyfill plugins.

I can add a PR for both of those and get your feedback

**Comment by nicolo-ribaudo** [comment]
Sounds good to me, feel free to open a PR for both!

**Comment by agilgur5** [comment]
Finally made some time for this and wrote up a PR to throw an error in #119 !

I didn't change the docs as `targets` have been removed from most options as of https://github.com/babel/babel-polyfills/commit/1091fa4e27a597148403545d21e776dadeb5c518 and my PR #116
