### ISSUE TITLE
@babel/helper-define-polyfill-provider throws syntax error on node 8

### ISSUE THREAD

**Issue by JLHwung** [babel/babel-polyfills#38]
See https://unpkg.com/@babel/helper-define-polyfill-provider@0.0.3/lib/normalize-options.js L10
```js
function patternToRegExp(pattern) {
  if (pattern instanceof RegExp) return pattern;

  try {
    return new RegExp(`^${pattern}$`);
  } catch {
    return null;
  }
}
```
Node 8 does not support optional catch binding and it should have been transpiled according to the root config.

https://github.com/babel/babel-polyfills/blob/7999657fce705d365420c2918687d54d365e1f52/babel.config.js#L14

(Did you specify `NODE_ENV=production` before `yarn build`? 😛)

**Comment by nicolo-ribaudo** [comment]
Fixed in 0.0.4. Thanks!

https://unpkg.com/@babel/helper-define-polyfill-provider@0.0.4/lib/normalize-options.js
