### ISSUE TITLE
Unnecessary polyfilling + wrongly renaming imports

### ISSUE THREAD

**Issue by anilanar** [babel/babel-polyfills#42]
I babelify + auto polyfill node_modules too; because it's usually unclear what ES version+browser libraries target nowadays. After switching to `babel-polyfills` (corejs3), one curious case failed.

For esm5/esm2015 builds of `rxjs@6.6.3`; in `node_modules/rxjs/_esm5/index.js`:
- `babel-polyfills` adds `import _Observable from "core-js-pure/features/observable/index.js";` at the top of the file.
- then replaces some (or all) occurences of the term `Observable` with `_Observable`.
- rxjs has a re-export `export { Observable } from './internal/Observable';`. `babel-polyfills` replaces that with `export { _Observable as Observable } from './internal/Observable';`
- bundler rightfully complains that there's no `_Observable` in `./internal/Observable`.

I see two problems here:
1) Why polyfill `Observable` in this case? `Observable` is imported (or re-exported) from somewhere, it's not the global `Observable`.
2) Even if it polyfills, why break the imports?

**Comment by anilanar** [comment]
It's actually the `proposals` flag that causes the issue (because Observable is a proposal), which is broken for `@babel/plugin-transform-runtime` too.

**Comment by nicolo-ribaudo** [comment]
Thanks for the bug report! It turns out this is not only for `proposals`, but it was a generic bug with `export ... from`.

**Comment by nicolo-ribaudo** [comment]
This will be fixed when babel/babel#12395 is released. In the meaintinme, you can exclude that file by adding `ignore: ["node_modules/rxjs/_esm5/index.js"]` to your Babel config.

PS. Thanks for testing these plugins!

**Comment by nicolo-ribaudo** [comment]
Fixed in `@babel/types@7.12.10`
