### ISSUE TITLE
Could not find module from core-js-pure

### ISSUE THREAD

**Issue by anilanar** [babel/babel-polyfills#44]
https://github.com/babel/babel-polyfills/blob/58f9f3b4fe4380a073dd0b50043e425a6f3714e3/packages/babel-plugin-polyfill-corejs3/test/fixtures/usage-pure/symbol-iterator-in/output.js

There's no `core-js-pure/stable/is-iterable.js` in `core-js-pure@3.7.0`.

**Comment by ljharb** [comment]
Was there in an earlier version of core-JS 3? If so, that’s a breaking change in a non major version.

**Comment by anilanar** [comment]
I don't think so, I specified the version just to be precise. It was probably all the same all along, by looking at core-js commit history.

**Comment by nicolo-ribaudo** [comment]
Yeah, it was just an error I made while implementing this plugin (I assumed that `core-js-pure/stable` and `core-js-pure/features` where the same thing except for proposals).

**Comment by utrolig** [comment]
Any estimate on this? I just encountered the exact same issue with `get-iterator.js` @nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
I'm waiting for a review from someone in the team, then I'll publish!

**Comment by nicolo-ribaudo** [comment]
Published in `babel-plugin-polyfill-corejs3@0.0.8`
