### ISSUE TITLE
Outputting absolute import paths in generated code

### ISSUE THREAD

**Issue by charlessuh** [babel/babel-polyfills#61]
Is there an ability to configure the import path of the generated output code to be absolute?

For example, instead of inserting output code like:

```
import "regenerator-runtime"
```

the desire is to insert output code like:

```
import "/my-project/node_modules/some-other-project/node_modules/regenerator-runtime"
```

For background, see the `absoluteRuntime` option in @babel/plugin-transform-runtime (see https://babeljs.io/docs/en/babel-plugin-transform-runtime#absoluteruntime)

> By default, transform-runtime imports from @babel/runtime/foo directly, but that only works if @babel/runtime is in the node_modules of the file that is being compiled. This can be problematic for nested node_modules, npm-linked modules, or CLIs that reside outside the user's project, among other cases. To avoid worrying about how the runtime module's location is resolved, this allows users to resolve the runtime once up front, and then insert absolute paths to the runtime into the output code.

**Comment by nicolo-ribaudo** [comment]
Yes! You should be able to do it with any polyfill provider: https://github.com/babel/babel-polyfills/blob/main/docs/usage.md#absoluteruntime

**Comment by charlessuh** [comment]
Awesome!
