### ISSUE TITLE
lodash.debounce for laterLogMissingDependencies delays process exit by 1 second

### ISSUE THREAD

**Issue by andersk** [babel/babel-polyfills#63]
The `lodash.debounce` for `laterLogMissingDependencies` adds a 1 second delay at process exit while it waits for the `setTimeout` to fire.

https://github.com/babel/babel-polyfills/blob/55f582c8ebc4b8a181a51fecaa92c89158cc7ac9/packages/babel-helper-define-polyfill-provider/src/dependencies.js#L95-L98

This is a really unfortunate side effect of the default `"deferred"` for `missingDependencies.log`. Can we change that default to `"per-file"`?

### Minimal reproducible example

**`babel.config.js`**

```js
module.exports = {
  presets: [["@babel/preset-env", { corejs: 3, useBuiltIns: "entry" }]],
};
```

**`hello.js`**

```js
console.log("Hello, world!");
```

Run

```console
$ yarn add @babel/core @babel/preset-env @babel/register core-js
…
info Direct dependencies
├─ @babel/core@7.13.1
├─ @babel/preset-env@7.13.5
├─ @babel/register@7.13.0
└─ core-js@3.9.0
…
$ export BABEL_DISABLE_CACHE=true  # to reproduce more than once
$ time node -r @babel/register hello.js
Hello, world!

real	0m1.366s
user	0m0.383s
sys	0m0.047s
```

There’s a 1 second delay after printing `Hello, world!` but before exit.

**Comment by nicolo-ribaudo** [comment]
Defaulting to `per-file` will produce an enormous output for some polyfills like `es-shims`, but I can:
- Reduce the delay from maybe 1 sec to 100ms
- Remove the delay for `core-js`, where it's mostly not needed.

**Comment by ljharb** [comment]
Can you elaborate more on `per-file` and why its impact varies by polyfill provider?

**Comment by nicolo-ribaudo** [comment]
When there is a missing dependency, this package logs about it.
We collect all the missing polyfills, and then log something like

```
Please run
  npm install polyfill-a polyfill-b polyfill-c polyfill-d
```

If we'd do that per-file, we cannot create a single command to copy-paste. It would look more like
```
Please run
  npm install polyfill-a polyfill-b
Please run
  npm install polyfill-c
Please run
  npm install polyfill-d
```

Where every log comes from a different file. `core-js` is a single package so it logs almost once, but for `es-shims` (which is a collection of a lot of different packages), it can log a very long list of command to run (in the worst case, max(number of files, number of polyfills)).

**Comment by ljharb** [comment]
gotcha. i guess i'm not sure why this needs to be debounced here instead of just ran once after everything's finished?

**Comment by nicolo-ribaudo** [comment]
Yes, because Babel plugins don't have the concept of "after compiling the project" but only "in this file" (this might change in the future, but not soon).

**Comment by ljharb** [comment]
ah, that's a painful limitation :-/
