### ISSUE TITLE
babel-polyfill for babel version '6.3.26'

### ISSUE THREAD

**Issue by Hripsime95** [babel/babel-polyfills#76]
Hi.
I need to add babel-polyfill to my project, in order to fix the issue with 'find' and 'includes' functions in ie11. The project is configured with gulp. I have a gulp task with babel configuration. In the project we use presets es2015. So I need to add babel polyfill but don't know how to add it. Please could you help me?

**Comment by nicolo-ribaudo** [comment]
These packages only support Babel 7. You could add `<script src="https://unpkg.com/core-js-bundle@3.9.1/minified.js"></script>` to load the whole `core-js` polyfill, or `https://unpkg.com/es5-shim@4.5.15/es5-shim.min.js`/`https://unpkg.com/es6-shim@0.35.6/es6-shim.min.js`.
