### ISSUE TITLE
ponyfills

### ISSUE THREAD

**Issue by thernstig** [babel/babel-polyfills#84]
The README.md has two "ponyfills" in them. 🐴-fills  😆

**Comment by ljharb** [comment]
Not sure of the point of this issue, but personally i find that term unnecessary (a shim is a self-installing polyfill; a polyfill is not self-installing), and also i find it denigrating.

**Comment by nicolo-ribaudo** [comment]
I think the point was that _I_ wrote ponyfills in the readme (because that was the only term I knew for "polyfills that not attach themselves to the global env"), but feel free to change it to something else.

**Comment by ljharb** [comment]
ah, i didn't even check :-) i'll update it, sure!

**Comment by thernstig** [comment]
It had the term `ponyfill` in the README.md. I was never denigrating anything.
