### ISSUE TITLE
Latest babel-plugin-polyfill-corejs3 is unpublished

### ISSUE THREAD

**Issue by chibibirdie** [babel/babel-polyfills#95]
Would it be possible to have a new version of https://github.com/babel/babel-polyfills/tree/main/packages/babel-plugin-polyfill-corejs3 published? We could use the fixes added here: https://github.com/babel/babel-polyfills/commit/d8653da761bd4f7d1b4ca09353306251bf84234d.

**Comment by nicolo-ribaudo** [comment]
I'll publish in a few hours.

**Comment by chibibirdie** [comment]
Thank you @nicolo-ribaudo!

**Comment by nicolo-ribaudo** [comment]
Done!
